hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7b83af5380faba6641a6fdf27e239eba79846f6b66a65da810860a8cb1e86ee4"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7e1f5788188341d69aa19bb057065d451fab494d002f96a1d92dbf5d7f3b5d2d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "5d3bfbab6b1af1525229e52889de5fd84fe44def5c25140d4bbe7d3daaccf2bf"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "c40a3498aa0c1bdb091b327b414c4adabe8618f1fc9a75614800c9fefef12977"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "ab6def9d98d3f5bf12f78845bdb770a19d5ca590c571e60184e537ffa14dcbee"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "565c943b5006c36137a2fe55e4b8433e134c3d1011a37c5f5124cee67b671cb8"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "82e70d274662876a9691d741a105c9762266ecac72f663e5c1d8f0e1bf35cc19"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3ff0c2f005f2523f157b776f0e870494a8e8ec0ff77cb7e965c88b4e2090efdb"
metafile = true
