name = "Vanilla Reimagined"
author = "BX Team"
version = "1.21.10-1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c4f97102e32f9a0fd92c2db49390b4038694c980ef489c7fe5c5a3af0818968"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
