name = "Vanilla Reimagined"
author = "BX Team"
version = "1.21.11-1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00691d1af70504492acef8bdeb87ecea60b585e83610a97aa44570c7912d6921"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
