name = "Vanilla Reimagined"
author = "BX Team"
version = "1.21.11-1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b416e54481b0aceeb4f189f8f14160fd1f3efc72fee9345f6da6e73137a4184"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
