name = "Vanilla Reimagined"
author = "BX Team"
version = "1.21.10-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f9f2cb911554177bf65e495e943674a4b4c3b887525dee96110b6b1ee650238"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]