name = "Vanilla Reimagined"
author = "BX Team"
version = "1.21.11-1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f17cd835ec0dfbe8618caadf545309a0d283cea4cea3845acd92dc0e9c0faf70"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
